#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Set application name
application=$(getApplication)

runApplication foamDictionary -entry writeFormat -set binary system/controlDict
runApplication blockMesh
runApplication makeAxialMesh -overwrite
runApplication collapseEdges -overwrite
runApplication checkMesh
